{"name": "Test User Not Found case", "status": "passed", "description": "\n    Validates the system's response when an operation is attempted on a non-existent user.\n    This test sends a request to an endpoint that requires a valid user.\n", "start": 1705608370993, "stop": 1705608370998, "uuid": "7d63d68d-2af4-4290-b9fc-2f9aebcfcd1f", "historyId": "bad64f7740f2cc062bbc813bb3bf2bcc", "testCaseId": "bad64f7740f2cc062bbc813bb3bf2bcc", "fullName": "test_jwt#test_user_not_found", "labels": [{"name": "tag", "value": "user_not_found"}, {"name": "suite", "value": "test_jwt"}, {"name": "host", "value": "hayarpi"}, {"name": "thread", "value": "22226-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_jwt"}]}